# Generated by Django 5.1.7 on 2025-04-24 04:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_tasktemplate_remove_task_is_dairy'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tasks.tasktemplate'),
        ),
    ]
